termMappings:
  https://lschema.org/DocumentNode:
  https://lschema.org/Value: Value
  https://lschema.org/Object: Object
  https://lschema.org/Array: Array
  https://lschema.org/attributeIndex: attributeIndex
  https://lschema.org/attributeName: attributeName
  https://lschema.org/has: has
  https://lschema.org/value: value
  https://lschema.org/schemaNodeId: schemaNodeId
  https://lschema.org/xml/ns: 
  https://lschema.org/entityId: entityId
  https://lschema.org/entityIdFields:
    
